### ISSUE TITLE
Suggest `func (ms *MicroStellar) Pay()` Should return transaction info

### ISSUE THREAD

**Issue by stphtt** [0xfe/microstellar#1]
I think it should return transaction info, something like [`horizon.TransactionSuccess`](https://godoc.org/github.com/stellar/go/clients/horizon#TransactionSuccess).

**Comment by 0xfe** [comment]
You can get the response from the last transaction via `ms.Response()`. (It returns a `TxResponse` which is a type alias for `horizon.TransactionSuccess`.

**Comment by stphtt** [comment]
@0xfe Thank you. I didn't know that.
